export const DAPP_APPROVAL_TIMEOUT_MS = 2 * 60 * 1000
export const DAPP_REQUEST_RESULT_TTL_MS = 2 * 60 * 1000
export const DAPP_STATUS_POLL_INTERVAL_MS = 500

export const DAPP_PROVIDER_REQUEST_TIMEOUT_DEFAULT_MS = 15_000
export const DAPP_PROVIDER_REQUEST_TIMEOUT_APPROVAL_MS = 150_000
